<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>AutoItX3.Assembly</AssemblyName>
        <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <PropertyGroup>
        <LangVersion>12.0</LangVersion>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup/>
    <ItemGroup>
        <Content Include="..\Module\AutoItX3.dll">
            <PackagePath>bin</PackagePath>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\Module\AutoItX3_x64.dll">
            <PackagePath>bin</PackagePath>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup/>
    <!-- <Reference Update="AutoItX3.dll">
      <Private>true</Private>
      <HintPath>..\Module\AutoItX3.dll</HintPath>
    </Reference>
    <Reference Update="AutoItX3_x64.dll">
      <Private>true</Private>
      <HintPath>..\Module\AutoItX3_x64.dll</HintPath>
    </Reference>
  </ItemGroup> -->
</Project>
